/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.spring.shivam;

import com.spring.shivam.com.spring.Bean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {



    public static void main(String[] args) {
        System.out.println("Main meth starts............... ");
        ApplicationContext context = new AnnotationConfigApplicationContext(Bean.class);
        Hello hello = (Hello) context.getBean("hello");
        System.out.println(hello.getMessage());
        System.out.println("Main meth ends.................  ");
    }
}
